### ISSUE TITLE
[Bug] Parser can't output parentheses.

### ISSUE THREAD

**Issue by MindXL** [MindXL/CCompilerInCpp#3]
**Describe the bug**

Parser can't output parentheses.

All the test cases for paring parentheses have already been annotated:
https://github.com/MindXL/CCompilerInCpp/blob/aa1c3b19a452bcd4dd6ecb7a05f26dcdc24b9472/test/test.cpp#L60

**To Reproduce**

1. Test the program's parser with any expression with parentheses in it, e.g. "1+(2+3)".
2. See error. The output would be like "1+2+3".

**Expected behavior**

Locate where to fix the parser when encounting parentheses.

**Comment by abel-mak** [comment]
Hi, i read the code maybe the problem is you lose track of parentheses here, i think the visitor can't make the difference between expression with parentheses and with not.
https://github.com/MindXL/CCompilerInCpp/blob/aa1c3b19a452bcd4dd6ecb7a05f26dcdc24b9472/src/Parser.cpp#L80-L83

**Comment by MindXL** [comment]
@abel-mak 

I think you are absolutely right. The vistor can't tell the difference.

**Comment by MindXL** [comment]
I came up with some solutions, but none of them satisfied me enough. Maybe that's because I'm just starting compiler theory.

I think I can create a new base class called "ParenthesesWrappedAstNode" or something that inherits from "AstNode".

https://github.com/MindXL/CCompilerInCpp/blob/aa1c3b19a452bcd4dd6ecb7a05f26dcdc24b9472/src/AstNode.h#L15-L20

It has a public bool member called "wrapped". You see, statements can't be wrapped with parentheses, so "StatementNode" inherits from "AstNode"; expressions can be wrapped, so they inherits from "...WrappedNode". Then, in "PrintVisitor", I can add parentheses provided "wrapped" is true.

The reason why I feel this solution not satisfactory enough is because it just adds a class. I don't think adding a new class for just one member is reasonable, but this is the best idea I have. In the meantime, I feel there gotta be a better way.

**Comment by abel-mak** [comment]
@MindXL How about to add wrapped variable to BinaryNode: https://github.com/MindXL/CCompilerInCpp/blob/ee5566dc9f54675ec18568706e7fcddb391e8368/src/AstNode.h#L89

**Comment by MindXL** [comment]
@abel-mak Do you mean only BinaryNode? But each node is independent. After being parsed here, the return value of "parseExpr()" could be different types of node:
https://github.com/MindXL/CCompilerInCpp/blob/ee5566dc9f54675ec18568706e7fcddb391e8368/src/Parser.cpp#L164-L170

I've started a new branch and modified the code according to my idea above, and it passed the test cases successfully. I may use the code here eventually.
https://github.com/MindXL/CCompilerInCpp/commit/06b0f7d45a3512ac333ad216ef257d80400c5c71#diff-806237dd6732cc8c883891737f7a5bd7857da31e468378c080bb2e4db6fdd394R22-R28

**Comment by MindXL** [comment]
By the way, although the parser is unable to output parentheses, the result of compilation is correct. Because lexer does a good job and is able to create a correct syntax tree. Thereout, each expression has a correct priority.

**Comment by abel-mak** [comment]
what you did is similar to what i sayed, but i meant it for just BinaryNode to be PwAstNode, but yeah all the other nodes can wrapped in parentheses, i think this is good idea i hope is solve the problem
> I've started a new branch and modified the code according to my idea above, and it passed the test cases successfully. I may use the code here eventually. [06b0f7d#diff-806237dd6732cc8c883891737f7a5bd7857da31e468378c080bb2e4db6fdd394R22-R28](https://github.com/MindXL/CCompilerInCpp/commit/06b0f7d45a3512ac333ad216ef257d80400c5c71#diff-806237dd6732cc8c883891737f7a5bd7857da31e468378c080bb2e4db6fdd394R22-R28)

**Comment by MindXL** [comment]
@abel-mak  I'll try your method. Thanks so much and I feel great about this discussion. xd
